project/urls.py
from django.conf.urls import url

from  . import  views

app_name ='project'
urlpatterns =[
    # ex: //project/
    # url(r'^$',views.index, name='index'),
     url(r'^$',views.IndexView.as_view(), name='index'),
    # ex:/project/5/detail
    #url(r'^(?P<question_id>[0-9]+)/$',views.detail,name='detail'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(), name='detail'),
    # ex: /project/5/results/
    #url(r'^(?P<question_id>[0-9]+)/results/$', views.results,name='results'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(),name='results'),
    #ex: /project/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name='vote'),
    #url(r'^(?P<question_id>[0-9]+)/vote/$',views.VoteView.as_view(),name='vote'),
    ]

project/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Question(models.Model):
      question_text = models.CharField(max_length=200)
      pub_date = models.DateTimeField('date published')

class Choice(models.Model):
      question = models.ForeignKey(Question,on_delete=models.CASCADE)
      choice_text = models.CharField(max_length=200)
      votes= models.IntegerField(default=0)

project/views.py
from django.shortcuts import render
from django.shortcuts import Http404
from django.shortcuts import HttpResponseRedirect, HttpResponse
from django.shortcuts import reverse
from django.shortcuts import get_object_or_404, render
from django.views     import generic


from .models import Question,Choice

# Create your views here.

#def index(request):
    #return HttpResponse("Hello, world. You're at the project index.")
#def index(request):
#    lastest_question_list = Question.objects.order_by('-pub_date')[:5]
#     output =', '.join([q.question_text for q in latest_question_list])
#      return HttpResponse(output)
#    context ={'latest_question_list':lastest_question_list}
#    return render (request,'project/index.html',context)

#leave the rest of the views (detail,results,vote) unchanged

class IndexView(generic.ListView):
      template_name ='project/index.html'
      context_object_name = 'lastest_question_list'
      
      def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by ('-pub_date')[:5]

class  DetailView(generic.DetailView):
       model=Question
       template_name= 'project/detail.html'
       
class  ResultsView(generic.DetailView):
       model=Question
       template_name='project/results.html'
 
def detail(request ,question_id):
        question =get_object_or_404(Question, pk=question_id)
        #try:
        # question=Question.objects.get(pk=question_id)
        #except Question.DoesNotExist:
         #  raise Http404("Question does not exist")
        return render( request,'project/detail.html',{'question': question})
    #return HttpResponse("You' re looking at question %s." % question_id)
    
def results(request,question_id):
         #response ="You're looking at the results of question %s."
         question =get_object_or_404(Question,pk=question_id)
         return render(request,'project/results.html',{'question':question})
     
def vote(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    try:
       selected_choice=question.choice_set.get(pk=request.POST['choice'])
    except(keyError,Choice.DoesNotExist):
       # Redisplay the question voting form.
       return render(request, 'project/detail.html',
              {'question': question,
               'error_message':"You didn't select a choice.",
              })
    else:
         selected_choice.votes +=1
         selected_choice.save()
         #Always return an httpResonseRedirect after successfully dealing
         #with POST data. This prevents data from being posted twice if a
         #user hits the back button.
         return HttpResponseRedirect(reverse('project:results',args=(question.id,)))
    #return HttpResponse("You're voting on question %s." %  question_id)

project/templates/project/detail.html
<h2>{{question.question_text}}</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'project:vote' question.id %}" method="post">
{% csrf_token %} 
{% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}" />
        <label for ="choice{{forloop.counter}}">{{choice.choice_text}}</label><br/>
{% endfor %}
<input type="submit" value="votes"/>
</form>

project/templates/project/index.html
{% if lastest_question_list %}
        <ul>
          { % for question in lastest_question_list % }
                <li><a href="/project/{{question.id}}/"> {{question.question_text}}</a></li>
          </ul>
          {%endfor%}
{% else %}
         <p> No project are avaiable .</p>
{% endif %}

project/templates/project/results.html
<h1>{{question.question_text}}</h1>

<ul>
{% for choice in question.choice_set.all %}
     <li>{{ choice.choice_text}} -- {{choice.vote}} vote{{choice.vote|pluralize}}</li>   
{% endfor %}      
</ul>

<a href="{% url 'project:detail' question.id %}" > Vote again</a>